fuzz:
  build_directory: artifacts
  ide: hardhat
  sources_directory: contracts
  deployed_contract_address: '0x5FbDB2315678afecb367f032d93F642f64180aa3'
  additional_contracts_addresses:
    - '0xe7f1725e7734ce288f8367e1bb143e90bb3f0512'
    - '0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9'
    - '0x5fc8d32690cc91d4c39d9d3abcbd16989f875707'
    - '0xa513e6e4b8f2a923d98304ec87f64353c4d5c853'
    - '0x8a791620dd6260079bf849dc5567adc3f2fdc318'
    - '0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e'
    - '0xa51c1fc2f0d1a1b8494ed1fe312d7c3a78ed91c0'
  number_of_cores: 1
  time_limit: 4h
  project: Dropps
  campaign_name_prefix: Dropps
  rpc_url: 'http://localhost:8545'
  faas_url: 'http://fuzzing.diligence.tools'
  targets:
    - contracts/Oracles.sol
    - contracts/merkles/MerkleDistributor.sol
    - contracts/mocks/BeaconDepositMock.sol
    - contracts/pool/FeesEscrow.sol
    - contracts/pool/Pool.sol
    - contracts/pool/PoolValidators.sol
    - contracts/presets/OwnablePausable.sol
    - contracts/presets/OwnablePausableUpgradeable.sol
    - contracts/tokens/Rewards.sol
    - contracts/tokens/StakedLyxToken.sol
