fuzz:
  build_directory: artifacts
  ide: hardhat
  sources_directory: contracts
  deployed_contract_address: '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0'
  additional_contracts_addresses:
    - '0x5FbDB2315678afecb367f032d93F642f64180aa3'
    - '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512'
    - '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9'
    - '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9'
    - '0x5FC8d32690cc91D4c39d9d3abcBD16989F875707'
    - '0x0165878A594ca255338adfa4d48449f69242Eb8F'
    - '0xa513E6E4b8f2a923D98304ec87F64353C4D5C853'
  number_of_cores: 1
  time_limit: 4h
  project: Dropps
  campaign_name_prefix: Dropps
  rpc_url: 'http://localhost:8545'
  faas_url: 'http://fuzzing.diligence.tools'
  targets:
    - contracts/Oracles.sol
    - contracts/merkles/MerkleDistributor.sol
    - contracts/mocks/BeaconDepositMock.sol
    - contracts/pool/FeesEscrow.sol
    - contracts/pool/Pool.sol
    - contracts/pool/PoolValidators.sol
    - contracts/presets/OwnablePausable.sol
    - contracts/presets/OwnablePausableUpgradeable.sol
    - contracts/tokens/Rewards.sol
    - contracts/tokens/StakedLyxToken.sol
